trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'

stages:
- stage: QualityAndTest
  displayName: 'Quality and Unit Test'
  jobs:
  - job: RunTests
    displayName: 'Pytest & Sonar Analysis'
    steps:
    - checkout: self
      fetchDepth: 0

    # 引用 pipelines 資料夾中的 templates
    - template: pipelines/steps-setup.yml
    
    - script: |
        python scripts/metrics_logger.py
      displayName: 'Initialize Metrics'

    - template: pipelines/steps-tests.yml
    - template: pipelines/steps-sonar.yml

- stage: Performance
  displayName: 'Performance Measurement'
  dependsOn: QualityAndTest
  jobs:
  - job: Benchmark
    steps:
    - template: pipelines/steps-setup.yml
    - template: pipelines/steps-metrics.yml
