parameters:
- name: runbook_name
  displayName: Runbook
  type: string
  default: create_project
  values:
  - create_project
  - modify_member

- name: project_name
  displayName: Project name
  type: string
  default: ''

- name: repo_name
  displayName: Repo name
  type: string
  default: ''

- name: manager_email
  displayName: Project Manager email
  type: string
  default: ''

- name: member_email
  displayName: Project Member email
  type: string
  default: ''

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Set up Python'

- script: |
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/src
    echo "Selected runbook: ${{ parameters.runbook_name }}"

    python scripts/run_runbook.py \
      --runbook-name "${{ parameters.runbook_name }}" \
      --project-name "${{ parameters.project_name }}" \
      --repo-name "${{ parameters.repo_name }}" \
      --manager-email "${{ parameters.manager_email }}" \
      --member-email "${{ parameters.member_email }}"
  displayName: 'Run selected runbook'
  env:
    ADO_ORG_URL: $(ADO_ORG_URL)
    ADO_PAT: $(AZURE_DEVOPS_PAT)
